alias: Lights on when motion office
trigger:
- entity_id: binary_sensor.presence_24
  platform: state
  from: 'off'
  to: 'on'
condition:
- condition: numeric_state
  below: '5'
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
action:
- data:
    entity_id: group.office_lights
  service: light.turn_on