alias: Garbage out tomorrow
description: >-
  Notify via Google speakers which garbage has to go out tomorrow morning.
triggers:
  - trigger: time
    at: "20:30:00"
conditions:
  condition: not
  conditions:
    - condition: state
      entity_id: sensor.afvalinfo_home_trash_type_tomorrow
      state: "geen"
actions:
  - data:
      entity_id:
        - media_player.living_room_display
      message: Morgen moet het volgende afval naar buiten, {{ states('sensor.afvalinfo_home_trash_type_tomorrow') }}
      language: nl-NL
    action: tts.cloud_say
