alias: CO alarm passage battery
description: >-
  The battery of the co alarm passage is almost empty
trigger:
  - entity_id: binary_sensor.passage_co_sensor_low_battery
    platform: state
    to: "on"
condition: []
action:
  - data:
      message: >-
        "Batterij van koolmonoxide alarm overloop is bijna leeg"
    service: notify.telegram_notify
