alias: CO alarm passage
description: >-
  The CO alarm in the passage is triggered
triggers:
  - entity_id: binary_sensor.passage_co_sensor_carbon_monoxide
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: "Koolmonoxide op de overloop gaat af!"
    action: notify.telegram_notify
