alias: CO alarm passage battery
description: >-
  The battery of the co alarm passage is almost empty
triggers:
  - entity_id: binary_sensor.passage_co_sensor_battery_low
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: >-
        "Batterij van koolmonoxide alarm overloop is bijna leeg"
    action: notify.telegram_notify
