alias: Smoke alarm passage battery
description: >-
  The battery of the smoke alarm passage is almost empty
trigger:
  - entity_id: binary_sensor.passage_smoke_sensor_battery_low
    platform: state
    to: "on"
condition: []
action:
  - data:
      message: >-
        "Batterij van brandalarm overloop is bijna leeg"
    action: notify.telegram_notify
