alias: Smoke alarm hallway battery
description: >-
  The battery of the smoke alarm hallway is almost empty
triggers:
  - entity_id: binary_sensor.hallway_smoke_sensor_battery_low
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: >-
        "Batterij van brandalarm gang is bijna leeg"
    action: notify.telegram_notify
