alias: Smoke alarm hallway
description: >-
  The smoke alarm in the hallway is triggered
triggers:
  - entity_id: binary_sensor.hallway_smoke_sensor_smoke
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: "Brandalarm op de gang gaat af!"
    action: notify.telegram_notify
