alias: Smoke alarm passage battery
description: >-
  The battery of the smoke alarm passage is almost empty
triggers:
  - entity_id: binary_sensor.passage_smoke_sensor_battery_low
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: >-
        "Batterij van brandalarm overloop is bijna leeg"
    action: notify.telegram_notify
