alias: Smoke alarm passage
description: >-
  The smoke alarm in the passage is triggered
triggers:
  - entity_id: binary_sensor.passage_smoke_sensor_smoke
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: "Brandalarm op de overloop gaat af!"
    action: notify.telegram_notify
