alias: 'Motion detected on driveway'
trigger:
- entity_id: binary_sensor.oprit
  platform: state
  to: 'on'
condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) - as_timestamp(states.automation.motion_detected_on_driveway.attributes.last_triggered) | int > 60 }}"
action:
- data:
    entity_id: image_processing.doods_driveway_camera
  service: image_processing.scan