- id: '1732120240406'
  alias: Test
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.gavin
    - person.jimini
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: person.gavin
      state: home
    - condition: state
      entity_id: person.jimini
      state: home
  actions:
  - device_id: 49b026b02dc9b77b85a3e2395afa5ed0
    domain: climate
    entity_id: 4dfd5c9a6f08eac750cfc44bc62d88f9
    type: set_preset_mode
    preset_mode: away
  mode: single
- id: '1732120450422'
  alias: Test2
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.gavin
    - person.jimini
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.gavin
      state: home
    - condition: state
      state: home
      entity_id: person.jimini
  actions:
  - device_id: 49b026b02dc9b77b85a3e2395afa5ed0
    domain: climate
    entity_id: 4dfd5c9a6f08eac750cfc44bc62d88f9
    type: set_preset_mode
    preset_mode: home
  mode: single
