homeassistant:
  # Load packages
  packages: !include_dir_named integrations

  latitude: !secret lat
  longitude: !secret lon
  country: NL
  elevation: 15
  unit_system: metric
  time_zone: Europe/Amsterdam
  allowlist_external_dirs:
    - "/config/www"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Enable ffmpeg for Eufy
ffmpeg:
