homeassistant:
  # Load packages
  packages: !include_dir_named integrations

  latitude: !secret lat
  longitude: !secret lon
  elevation: 15
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home
  allowlist_external_dirs:
    - "/config/www"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
