homeassistant:
  # Load packages
  packages: !include_dir_named integrations
  
  latitude: !secret lat 
  longitude: !secret lon 
  elevation: 15
  unit_system: metric
  time_zone: Europe/Amsterdam
  name: Home
  whitelist_external_dirs:
  - "/config/www"