version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /home/gavin/hass/hass-config:/config
    restart: always
    network_mode: host
#    devices:
#      - /dev/ttyACM0:/dev/ttyACM0
