alias: Living room activate default light scene
description: >-
  Activate the default light scene when the mediaplayer stops.
trigger:
  - platform: state
    entity_id: media_player.xbian
    from: "playing"
    to: "idle"
condition:
  - condition: numeric_state
    below: "5"
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
action:
  - data:
      entity_id: script.living_room_lights_default
    service: script.turn_on
