alias: Hyperion off
trigger:
- platform: state
  entity_id: media_player.xbian
  from: 'playing'
  to: 'idle'
  for:
    minutes: 5
condition: []
action:
- data:
    entity_id: light.hyperion
  service: light.turn_off