alias: Activate movie scene
trigger:
  - platform: state
    entity_id: media_player.xbian
    from: 'idle'
    to: 'playing'
condition:
- condition: numeric_state
  below: '5'
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
action:
- data:
    entity_id: script.movie_scene
  service: script.turn_on
- data:
    entity_id: light.hyperion
    effect: V4L
  service: light.turn_on