alias: Lights on when motion guest bedroom
trigger:
- entity_id: binary_sensor.presence_22
  platform: state
  from: 'off'
  to: 'on'
condition:
- condition: numeric_state
  below: '5'
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
action:
- data:
    entity_id: light.dimmable_light_10
  service: light.turn_on