alias: Ambilight on when shield turns on
description: >-
  Activate the ambilight when turning on media player.
trigger:
  - platform: state
    entity_id: media_player.shield_parent
    to: "on"
condition: []
action:
  - data:
      entity_id: light.tvambilight
    service: light.turn_on
