alias: Ambilight on when shield is playing
description: >-
  Activate the ambilight when starting media player.
trigger:
  - platform: state
    entity_id: media_player.shield
    to: "playing"
condition: []
action:
  - data:
      entity_id: light.tvambilight
    service: light.turn_on
