alias: Ambilight off when shield is playing
description: >-
  Deactivate the ambilight when stopping media player.
trigger:
  - platform: state
    entity_id: media_player.shield
    from: "playing"
condition: []
action:
  - data:
      entity_id: light.tvambilight
    service: light.turn_off
