alias: Ambilight on when shield turns off
description: >-
  Deactivate the ambilight when turning off media player.
trigger:
  - platform: state
    entity_id: media_player.shield_parent
    to: "off"
condition: []
action:
  - data:
      entity_id: light.tvambilight
    service: light.turn_off
