alias: Dogcam camera nightmode off
description: >-
  Turn nightmode of dogcam and spin it to the the living room at 7am
trigger:
  - platform: time
    at: "07:00:00"
condition: []
action:
  - data:
      entity_id: switch.dogcam_camera_night_mode
    service: switch.turn_off
  - data:
      entity_id: cover.dogcam_camera_move_left_right
      position: 85
    service: cover.set_cover_position
