alias: Frontyard christmas lights on in the evening
description: >-
  Turn christmas lights in the frontyard on in the backyard on sunset.
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: -1
condition: []
action:
  - data:
      entity_id: light.christmas_lights_front
    service: light.turn_on
