alias: Living room activate default light scene
description: >-
  Activate the default light scene when the media player stops.
triggers:
  - trigger: state
    entity_id: media_player.shield
    from: "playing"
conditions:
  - condition: numeric_state
    below: 5
    entity_id: sun.sun
    attribute: elevation
actions:
  - data:
      entity_id: script.exit_movie_scene
    action: script.turn_on
