alias: Living room activate default light scene
description: >-
  Activate the default light scene when the media player stops.
trigger:
  - platform: state
    entity_id: media_player.shield
    from: "playing"
condition:
  - condition: numeric_state
    below: 5
    entity_id: sun.sun
    attribute: elevation
action:
  - data:
      entity_id: script.living_room_lights_default
    action: script.turn_on
