alias: Living room activate default light scene
description: >-
  Activate the default light scene when the mediaplayer stops.
trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    from: "playing"
condition:
  - condition: numeric_state
    below: 5
    entity_id: sun.sun
    attribute: elevation
action:
  - data:
      entity_id: script.living_room_lights_default
    service: script.turn_on
