alias: Living room lights off
description: >-
  Turn lights off when there is no motion for 20 minutes.
triggers:
  - entity_id: binary_sensor.living_room_motion_sensor_occupancy
    trigger: state
    to: "off"
    for:
      minutes: 20
conditions:
  not:
    - condition: state
      entity_id: media_player.shield
      state: "playing"
actions:
  - data:
      entity_id: light.living_room_lights
    action: light.turn_off
  - data:
      entity_id: light.wled_living_room
    action: light.turn_off
