alias: Living room lights on when motion
description: >-
  Turn lights on when there is motion and after sunset.
trigger:
  - entity_id: binary_sensor.livingroom_motion_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    below: 2
    entity_id: sun.sun
    attribute: elevation
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
        state: "playing"
action:
  - data:
      entity_id: light.livingroom_lights
    service: light.turn_on
