alias: Living room lights on
description: >-
  Turn lights on when there is motion and after sunset.
trigger:
  - entity_id: binary_sensor.livingroom_motion_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  and:
    - condition: numeric_state
      below: 4
      entity_id: sun.sun
      attribute: elevation
    - not:
        - condition: state
          entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
          state: "playing"
action:
  - data:
      entity_id: light.livingroom_lights
    service: light.turn_on
