alias: Living room lights on
description: >-
  Turn lights on when there is motion and after sunset.
triggers:
  - entity_id: binary_sensor.living_room_motion_sensor_occupancy
    trigger: state
    to: "on"
conditions:
  and:
    - condition: numeric_state
      below: 4
      entity_id: sun.sun
      attribute: elevation
    - not:
        - condition: state
          entity_id: media_player.shield
          state: "playing"
actions:
  - data:
      entity_id: script.living_room_lights_default
    action: script.turn_on
