alias: Living room lights off
description: >-
  Turn lights off when there is no motion for 20 minutes.
trigger:
  - entity_id: binary_sensor.livingroom_motion_sensor
    platform: state
    to: "off"
    for:
      minutes: 20
condition:
  not:
    - condition: state
      entity_id: media_player.shield
      state: "playing"
action:
  - data:
      entity_id: light.livingroom_lights
    service: light.turn_off
