alias: Living room lights on
description: >-
  Turn lights on when there is motion and after sunset.
trigger:
  - entity_id: binary_sensor.livingroom_motion_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    below: "5"
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.plex_plex_for_lg
        state: "playing"
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.plex_plex_for_lg
        state: "paused"
action:
  - data:
      entity_id: light.livingroom_lights
    service: light.turn_on
