alias: Living room lights toggle on press
description: >-
  Turns all the living room lights on/off on click Tradfri remote.
triggers:
  - entity_id: sensor.living_room_switch_action
    trigger: state
    to: "toggle"
conditions: []
actions:
  - data:
      entity_id: light.living_room_lights
    action: light.toggle
  - data:
      entity_id: light.wled_living_room
    action: light.toggle
  # - data:
  #     entity_id: light.twinkly_f6bc91
  #   action: light.toggle
