alias: Living room lights on
description: >-
  Turn lights on when there is motion and after sunset.
trigger:
  - entity_id: binary_sensor.living_room_motion_sensor_occupancy
    platform: state
    to: "on"
condition:
  and:
    - condition: numeric_state
      below: 4
      entity_id: sun.sun
      attribute: elevation
    - not:
        - condition: state
          entity_id: media_player.shield
          state: "playing"
action:
  - data:
      entity_id: light.living_room_lights
    service: light.turn_on
  - data:
      entity_id: light.wled_living_room
    service: light.turn_on
  - data:
      entity_id: light.twinkly_f6bc91
    service: light.turn_on
