alias: Living room lights toggle on press
description: >-
  Turns all the living room lights on/off on click Tradfri remote.
trigger:
  - entity_id: sensor.living_room_switch_action
    platform: state
    to: "toggle"
condition: []
action:
  - data:
      entity_id: light.living_room_lights
    service: light.toggle
  - data:
      entity_id: light.wled_living_room
    service: light.toggle
  - data:
      entity_id: light.twinkly_f6bc91
    service: light.toggle
