# 2001 = button UP is held
# 2003 = button UP release
# 3001 = button DOWN is held
# 3003 = button DOWN released

alias: Livingroom lights dimming init
description: >-
  Initialize the dim function for the living room lights when holding the button down.
initial_state: "on"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "living_room_remote_control"
    event: 3001
condition: []
action:
  - data:
      variables:
        direction: down
        light: light.livingroom_lights
    service: script.turn_on
    entity_id: script.tradfri_lights_dimmer
