alias: Living room lights off
description: >-
  Turn lights off when there is no motion for 20 minutes.
trigger:
  - entity_id: binary_sensor.living_room_motion_sensor_occupancy
    platform: state
    to: "off"
    for:
      minutes: 20
condition:
  not:
    - condition: state
      entity_id: media_player.shield
      state: "playing"
action:
  - data:
      entity_id: light.living_room_lights
    service: light.turn_off
  - data:
      entity_id: light.wled_living_room
    service: light.turn_off
