alias: Living room activate movie scene
description: >-
  Activate the movie scene when starting media player.
trigger:
  - platform: state
    entity_id: media_player.shield
    to: "playing"
condition:
  - condition: numeric_state
    below: 5
    entity_id: sun.sun
    attribute: elevation
action:
  - data:
      entity_id: script.movie_scene
    service: script.turn_on
