alias: Living room activate movie scene
description: >-
  Activate the movie scene when starting media player.
triggers:
  - trigger: state
    entity_id: media_player.shield
    to: "playing"
conditions:
  and:
    - condition: numeric_state
      below: 5
      entity_id: sun.sun
      attribute: elevation
    - or:
        - not:
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: YouTube
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: Twitch
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: Spotify
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: "F1TV Chromecast"
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: "Videoland"
            - condition: state
              entity_id: media_player.shield
              attribute: app_name
              state: "Viaplay"
actions:
  - data:
      entity_id: script.movie_scene
    action: script.turn_on
