alias: WLED TV Turn off when Shield turn off
description: >-
  Turns the WLED Ambilight off when the NVidia Shield is turned off
trigger:
  - entity_id: media_player.shield
    platform: state
    to: "off"
condition: []
action:
  - data:
      entity_id: light.tvambilight
    service: light.turn_off
