alias: Lights off backyard
trigger:
- entity_id: binary_sensor.presence_17
  platform: state
  from: 'on'
  to: 'off'
  for:
    minutes: 5
condition: []
action:
- data:
    entity_id: light.achtertuin_spots
  service: light.turn_off