alias: Holiday turn on lights
description: >-
  Turn lights on when when we are on holiday.
triggers:
  trigger: time
  at: "19:45:00"
conditions: []
actions:
  - data:
      entity_id: light.holiday_lights
    action: light.turn_on
