alias: Holiday turn on lights
description: >-
  Turn lights on when when we are on holiday.
trigger:
  platform: time
  at: "19:45:00"
condition: []
action:
  - data:
      entity_id: light.holiday_lights
    service: light.turn_on
