alias: Holiday turn off lights
description: >-
  Turn lights off when when we are on holiday.
triggers:
  trigger: time
  at: "23:11:30"
conditions: []
actions:
  - data:
      entity_id: light.holiday_lights
    action: light.turn_off
