alias: Person detected on driveway
description: >-
  Send a message when there is a person detected on driveway when not home
trigger:
  platform: state
  entity_id: binary_sensor.person_on_driveway
  from: "off"
  to: "on"
  for:
    seconds: 3
condition:
  - condition: state
    state: not_home
    entity_id: device_tracker.poco_f1
action:
  - data:
      title: Send image person on driveway
      message: "Send image person on driveway"
      data:
        photo:
          - url: "http://192.168.2.17:5000/driveway/person/best.jpg"
            caption: "Er is een persoon op de oprit"
    service: notify.telegram_poco_f1
