alias: Driveway camera nightmode on
description: >-
  Turn the driveway camera nightmode on on sunset.
trigger:
  - platform: sun
    event: sunset
    offset: "00:00:00"
condition: []
action:
  - data:
      entity_id: switch.driveway_camera_night_mode
    service: switch.turn_on
