alias: Driveway camera nightmode on
description: >-
  Turn the driveway camera nightmode on on sunset.
triggers:
  - trigger: sun
    event: sunset
    offset: "00:00:00"
conditions: []
actions:
  - data:
      entity_id: switch.driveway_camera_night_mode
    action: switch.turn_on
