alias: Driveway camera nightmode off
description: >-
  Turn the driveway camera nightmode off on sunrise.
triggers:
  - trigger: sun
    event: sunrise
    offset: "00:00:00"
conditions: []
actions:
  - data:
      entity_id: switch.driveway_camera_night_mode
    action: switch.turn_off
