alias: Frontdoor lights turn on around sunset
description: >-
  Turn the frontdoor lights just after sunset
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    # Can be a positive or negative number
    below: -3.85
condition: []
action:
  - data:
      entity_id: light.frontdoor_lights
      brightness: 153
      transition: 1
    service: light.turn_on
