alias: Frontdoor lights turn off person detected
description: >-
  Turn lights on when there isnt a person detected anymore by the driveway camera
trigger:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    platform: state
    to: "off"
    for:
      minutes: 6
condition:
  - condition: time
    after: "05:00:00"
  - condition: time
    before: "12:00:00"
action:
  - data:
      entity_id: light.frontdoor_lights
      transition: 1
    action: light.turn_off
