alias: Frontdoor lights turn off at midnight
description: >-
  Turn the frontdoor lights off at 00.01AM
trigger:
  - platform: time
    at: "00:01:00"
condition: []
action:
  - data:
      entity_id: light.frontdoor_lights
      transition: 1
    action: light.turn_off
