alias: Frontdoor lights turn off at midnight
description: >-
  Turn the frontdoor lights off at 00.01AM
triggers:
  - trigger: time
    at: "00:01:00"
conditions: []
actions:
  - data:
      entity_id: light.frontdoor_lights
      transition: 1
    action: light.turn_off
