alias: Frontdoor lights turn on motion
description: >-
  Turn lights on when there is motion in the hallway in the morning
trigger:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    platform: state
    to: "on"
condition:
  - condition: time
    after: "05:00:00"
  - condition: sun
    before: sunrise
action:
  - data:
      entity_id: light.frontdoor_lights
      brightness: 254
      transition: 1
    service: light.turn_on
