alias: Frontdoor lights turn off person detected
description: >-
  Turn lights on when there isnt a person detected anymore by the driveway camera
triggers:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    trigger: state
    to: "off"
    for:
      minutes: 6
conditions:
  - condition: time
    after: "05:00:00"
  - condition: time
    before: "12:00:00"
actions:
  - data:
      entity_id: light.frontdoor_lights
      transition: 1
    action: light.turn_off
