alias: Frontdoor lights turn on person detected
description: >-
  Turn lights on when there is a person detected by the driveway camera
triggers:
  - entity_id: binary_sensor.driveway_person_occupancy
    trigger: state
    to: "on"
conditions:
  - condition: time
    after: "05:00:00"
  - condition: sun
    before: sunrise
actions:
  - data:
      entity_id: light.frontdoor_lights
      brightness: 254
      transition: 1
    action: light.turn_on
