alias: Frontdoor lights turn on motion
description: >-
  Turn lights on when there is motion in the hallway in the morning
triggers:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    trigger: state
    to: "on"
conditions:
  - condition: time
    after: "05:00:00"
  - condition: sun
    before: sunrise
actions:
  - data:
      entity_id: light.frontdoor_lights
      brightness: 254
      transition: 1
    action: light.turn_on
