alias: Frontdoor lights turn off motion
description: >-
  Turn lights off when there is no motion in the hallway in the morning
trigger:
  - entity_id: binary_sensor.hallway_motion_sensor
    platform: state
    to: "off"
    for:
      minutes: 1
condition:
  - condition: time
    after: "06:00:00"
  - condition: time
    before: "12:00:00"
action:
  - data:
      entity_id: light.frontdoor_lights
      transition: 1
    service: light.turn_off
# alias: Frontdoor lights turn off no motion
# description: >-
#   Turn lights off when there is no motion after sunset.
# trigger:
#   - entity_id: binary_sensor.doorbell_global_motion_sensor
#     platform: state
#     to: "False"
#     for:
#       minutes: 5
# condition:
#   - condition: time
#     after: "00:00:01"
#     before: "09:00:01"
# action:
#   - data:
#       entity_id: light.frontdoor_lights
#       transition: 1
#     service: light.turn_off
