alias: Nano is getting picked up
description: >-
  The Nano Tril sensor is triggert!
triggers:
  - entity_id: binary_sensor.aqara_trilling_sensor_vibration
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: "Nano is opgepakt!"
    action: notify.telegram_notify
