alias: Office lights on
description: >-
  Turn lights on when there is motion after sunset.
trigger:
  - entity_id: binary_sensor.office_motion_sensor_occupancy
    platform: state
    to: "on"
condition:
  - condition: numeric_state
    below: 4
    entity_id: sun.sun
    attribute: elevation
action:
  - data:
      entity_id: light.office_lights
    service: light.turn_on
  - data:
      entity_id: light.wled_office
    service: light.turn_on
