alias: Lights off office
trigger:
- entity_id: binary_sensor.presence_24
  platform: state
  from: 'on'
  to: 'off'
  for:
    minutes: 15
condition: []
action:
- data:
    entity_id: group.office_lights
  service: light.turn_off