alias: Lights in and around the closet on left press
description: >-
  Turns the big light and WLED light on left press
trigger:
  - entity_id: sensor.office_double_switch_action
    platform: state
    to: "single_left"
condition: []
action:
  - data:
      entity_id: light.office_standing_corner_light
    service: light.toggle
  - data:
      entity_id: light.wled_office
    service: light.toggle
