alias: Office lights toggle double click
description: >-
  Toggles all office lights on double click
triggers:
  - entity_id: sensor.office_double_switch_action
    trigger: state
    to: "single_both"
conditions: []
actions:
  - data:
      entity_id: light.office_lights
    action: light.toggle
  - data:
      entity_id: light.wled_office
    action: light.toggle
