alias: Office lights off
description: >-
  Turn lights off when there is no motion for 15 minutes.
trigger:
  - entity_id: binary_sensor.office_motion_sensor_occupancy
    platform: state
    to: "off"
    for:
      minutes: 15
condition: []
action:
  - data:
      entity_id: light.office_lights
    action: light.turn_off
  - data:
      entity_id: light.wled_office
    action: light.turn_off
