alias: Lights in and around the closet on left press
description: >-
  Turns the big light and WLED light on left press
triggers:
  - entity_id: sensor.office_double_switch_action
    trigger: state
    to: "single_left"
conditions: []
actions:
  - data:
      entity_id: light.office_corner_color_light
    action: light.toggle
  - data:
      entity_id: light.wled_office
    action: light.toggle
