alias: Office lights off
description: >-
  Turn lights off when there is no motion for 15 minutes.
trigger:
  - entity_id: binary_sensor.office_motion_sensor
    platform: state
    from: "on"
    to: "off"
    for:
      minutes: 15
condition: []
action:
  - data:
      entity_id: group.office_lights
    service: light.turn_off
