alias: Switch toggle lights office
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "xiaomi_double_button_switch_1"
    event: 3002
condition: []
action:
  - data:
      entity_id: group.office_lights
    service: light.toggle
