alias: Switch toggle kleurenlamp office
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "xiaomi_double_button_switch_1"
    event: 2002
condition: []
action:
- data:
    entity_id: light.color_light_9
  service: light.toggle