alias: Door fridge
trigger:
- entity_id: binary_sensor.openclose_25
  platform: state
  from: 'off'
  to: 'on'
  for:
    seconds: 60
condition: []
action:
- data:
    entity_id: script.door_fridge_open_init
  service: script.turn_on