alias: Alarm trigger to pending
trigger:
  - platform: state
    entity_id: group.alarm_triggers
    from: 'off'
    to: 'on'
condition: []
action:
- data:
    entity_id: alarm_control_panel.home_alarm
  service: alarm_control_panel.alarm_trigger