alias: Set climate preset to away
description: "Set the preset mode of climate to away when everyone is not home"
triggers:
  - trigger: zone
    entity_id:
      - person.gavin
      - person.jimini
    zone: zone.home
    event: leave
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: person.gavin
        state: home
      - condition: state
        entity_id: person.jimini
        state: home
actions:
  - action: climate.set_preset_mode
    metadata: {}
    data:
      preset_mode: away
    target:
      device_id: 49b026b02dc9b77b85a3e2395afa5ed0
mode: single
