alias: Climate Home
description: >-
  Set the preset of the climate to home when somebody comes home
trigger:
  - entity_id: group.alarm_triggers
    platform: state
    to: "on"
condition:
  - condition: time
    after: "07:00:00"
    before: "22:30:00"
action:
  - data:
      entity_id: climate.heating
      preset_mode: "home"
    service: climate.set_preset_mode
