alias: Climate Home
description: >-
  Set the preset of the climate to home when somebody comes home
trigger:
  - entity_id: group.phones
    platform: state
    from: "not_home"
    to: "home"
condition: []
action:
  - data:
      entity_id: climate.heating
      preset_mode: "home"
    service: climate.set_preset_mode
