alias: Turn christmas lights off midnight
description: "Turn off the christmas lights when its midnight"
triggers:
  - trigger: time
    at: 00:00:00
conditions: []
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.sonoff_christmas_frontyard
mode: single
