alias: Smoke alarm hallway battery
description: >-
  The battery of the smoke alarm hallway is almost empty
trigger:
  - entity_id: sensor.hallway_smoke_sensor_battery_level
    platform: numeric_state
    below: 15
condition: []
action:
  - data:
      message: >-
        "Batterij van brandalarm gang is bijna leeg - 
        ({{ states('sensor.hallway_smoke_sensor_battery_level')|int }}%)"
    service: notify.telegram_poco_f1
