alias: Frontdoor camera nightmode on
description: >-
  Turn the frontdoor camera nightmode on on sunset.
trigger:
  - platform: sun
    event: sunset
    offset: "00:00:00"
condition: []
action:
  - data:
      entity_id: switch.frontdoor_camera_night_mode
    service: switch.turn_on
  - data:
      entity_id: switch.frontdoor_camera_ir_filter
    service: switch.turn_on
  - data:
      entity_id: switch.frontdoor_camera_ir_led
    service: switch.turn_off
