alias: Frontdoor camera nightmode off
description: >-
  Turn the frontdoor camera nightmode off on sunrise.
trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:00"
condition: []
action:
  - data:
      entity_id: switch.frontdoor_camera_night_mode
    service: switch.turn_off
  - data:
      entity_id: switch.frontdoor_camera_ir_filter
    service: switch.turn_on
# Nightmode is a package with a few commandos for the cam
