alias: Doorbell
description: >-
  Play sound on the Google speakers and send a message/photo to phone.
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "lumi_sensor_switch_aq3"
    event: 1002
condition: []
action:
  - data:
      entity_id: media_player.living_room_display
      volume_level: 1.0
    service: media_player.volume_set
  - data:
      entity_id: media_player.office_home_mini
      volume_level: 1.0
    service: media_player.volume_set
  - data:
      entity_id: media_player.living_room_display
      media_content_id: http://192.168.2.17:8123/local/doorbell/doorbell.mp3
      media_content_type: audio/mp3
    service: media_player.play_media
  - data:
      entity_id: media_player.office_home_mini
      media_content_id: http://192.168.2.17:8123/local/doorbell/doorbell.mp3
      media_content_type: audio/mp3
    service: media_player.play_media

  - data:
      title: "Ik moest kloppen"
      message: "want de bel doet het niet"
      data:
        image: "http://192.168.2.17:5000/frontdoor/latest.jpg"
        channel: Doorbell
        importance: high
        vibrationPattern: "100, 1000, 100, 1000, 100, 1000"
    service: notify.mobile_app_poco_f1

  - data:
      entity_id: camera.frontdoor_camera
      filename: '/media/doorbell/doorbell_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
    service: camera.snapshot

  - delay: "00:00:05"

  - data_template:
      entity_id: media_player.living_room_display
      volume_level: 0.6
    service: media_player.volume_set
  - data_template:
      entity_id: media_player.office_home_mini
      volume_level: 0.6
    service: media_player.volume_set

  # - data:
  #     title: Send image of the person at the door
  #     message: "Send image of the person at the door"
  #     data:
  #       photo:
  #         - url: "http://192.168.2.17:5000/frontdoor/latest.jpg"
  #           caption: "Er staat iemand voor de deur"
  #   service: notify.telegram_poco_f1

  # - data:
  #     url: !secret still_img_frontdoor_camera
  #     username: !secret camera_user
  #     password: !secret camera_pass
  #     verify_ssl: false
  #     caption: "Er staat iemand voor de deur"
  #   service: telegram_bot.send_photo
