alias: Hallway lights on
description: >-
  Turn lights on when there is motion and after sunset.
triggers:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    trigger: state
    to: "on"
conditions:
  - condition: numeric_state
    below: 4
    entity_id: sun.sun
    attribute: elevation
actions:
  - data:
      entity_id: light.hallway_lights
      brightness_pct: 32
    action: light.turn_on
