alias: Lights off hallway
trigger:
  - entity_id: binary_sensor.motion_sensor_3
    platform: state
    from: "on"
    to: "off"
condition: []
action:
  - data:
      entity_id: group.hallway_spots
    service: light.turn_off
