alias: Hallway lights off
description: >-
  Turn lights off when there is no motion.
triggers:
  - entity_id: binary_sensor.hallway_motion_sensor_occupancy
    trigger: state
    to: "off"
conditions: []
actions:
  - data:
      entity_id: light.hallway_lights
    action: light.turn_off
