alias: Shed lights off
description: >-
  Turn lights off when there is no motion for 1 minute.
trigger:
  - entity_id: binary_sensor.shed_motion_sensor_occupancy
    platform: state
    to: "off"
    for:
      minutes: 1
condition: []
action:
  - data:
      entity_id: light.shed_light
    service: light.turn_off
