alias: Shed lights off
description: >-
  Turn lights off when there is no motion for 1 minute.
triggers:
  - entity_id: binary_sensor.shed_motion_sensor_occupancy
    trigger: state
    to: "off"
    for:
      minutes: 1
conditions: []
actions:
  - data:
      entity_id: light.shed_light
    action: light.turn_off
