alias: Shed lights on
description: >-
  Turn lights on when there is motion
triggers:
  - entity_id: binary_sensor.shed_motion_sensor_occupancy
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      entity_id: light.shed_light
    action: light.turn_on
