# "Killswitch for the lights. In a few cases the lights are still on in the middle of the night"
alias: Killswitch lights
description: >-
  Turn all the lights off at 2AM, as a double check so that no light is on the whole night long
triggers:
  - trigger: time
    at: "01:30:00"
conditions: []
actions:
  - data:
      entity_id: light.living_room_lights
    action: light.turn_off
  - data:
      entity_id: light.kitchen_lights
    action: light.turn_off
  # - data:
  #     entity_id: light.twinkly_f6bc91
  #   action: light.turn_off

  - delay:
      seconds: 2

  - data:
      entity_id: light.hallway_lights
    action: light.turn_off
  - data:
      entity_id: light.office_lights
    action: light.turn_off

  - delay:
      seconds: 2

  - data:
      entity_id: light.backyard_spots
    action: light.turn_off
  - data:
      entity_id: light.shed_light
    action: light.turn_off

  - delay:
      seconds: 2

  - data:
      entity_id: light.wled_living_room
    action: light.turn_off
  - data:
      entity_id: light.wled_office
    action: light.turn_off
