alias: System recorder repack
description: >-
  Repack recorder database
mode: single
triggers:
  - trigger: time
    at: "05:00"
conditions:
  - condition: time
    weekday:
      - sun
actions:
  - action: recorder.purge
    data:
      repack: true
