alias: System recorder repack
description: >-
  Repack recorder database
mode: single
trigger:
  - platform: time
    at: "05:00"
condition:
  - condition: time
    weekday:
      - sun
action:
  - action: recorder.purge
    data:
      repack: true
