alias: Washing machine water battery
description: >-
  The battery of the washing machine water detection is almost empty
triggers:
  - entity_id: binary_sensor.washing_machine_water_sensor_battery_low
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: >-
        Batterij van water detectie wasmachine is bijna leeg
    action: notify.telegram_notify
