alias: Washing machine water detected
description: >-
  The water alarm behind the washing machine is triggered
triggers:
  - entity_id: binary_sensor.washing_machine_water_sensor_water_leak
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      message: "Er is water gedetecteerd achter de wasmachine!"
    action: notify.telegram_notify
