alias: Door Fridge
description: >-
  TTS to Google speakers when the fridge door is open for longer then 60 seconds. Repeats every 20 seconds until closed.
trigger:
  - entity_id: binary_sensor.fridge_door_sensor
    platform: state
    from: "off"
    to: "on"
    for:
      seconds: 60
condition: []
action:
  - data:
      entity_id: script.fridge_open_init
    service: script.turn_on
