alias: Kitchen lights dimmer on hold down
description: >-
  Turn the lights dimmer when hold-press the switch down.
triggers:
  - entity_id: sensor.kitchen_switch_action
    trigger: state
    to: "brightness_step_down"
conditions: []
actions:
  - data:
      entity_id: light.kitchen_lights
      brightness_step_pct: -10
    action: light.turn_on
