alias: Kitchen lights on single press
description: >-
  Turn lights on when single-press the switch up.
trigger:
  - entity_id: sensor.kitchen_switch_action
    platform: state
    to: "on"
condition: []
action:
  - data:
      entity_id: light.kitchen_lights
      brightness_pct: 45
    action: light.turn_on
