alias: Kitchen lights of single press
description: >-
  Turn lights off when single-press the switch down.
trigger:
  - entity_id: sensor.kitchen_switch_action
    platform: state
    to: "off"
condition: []
action:
  - data:
      entity_id: light.kitchen_lights
    action: light.turn_off
