alias: Kitchen lights off press toggle
description: >-
  Turn lights off when single-press the toggle button.
triggers:
  - entity_id: sensor.kitchen_switch_action
    trigger: state
    to: "off"
conditions: []
actions:
  - data:
      entity_id: light.kitchen_lights
    action: light.turn_off
