# 1001 = button UP is held
# 1003 = button UP release
# 2001 = button DOWN is held
# 2003 = button DOWN released

alias: Kitchen lights brighten init
description: >-
  Initialize the brighten function for the kitchen lights when holding the button up.
initial_state: "on"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "kitchen_on_off_switch"
    event: 1001
condition: []
action:
  - data:
      variables:
        direction: up
        light: light.kitchen_lights
    service: script.turn_on
    entity_id: script.kitchen_lights_dimmer
