alias: Lights on when motion kitchen
trigger:
  - entity_id: binary_sensor.motion_sensor_2
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    below: "5"
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
action:
  - data:
      entity_id: light.keuken_spots
      # brightness: 115
    service: light.turn_on
