alias: Kitchen lights on
description: >-
  Turn lights on when there is motion after sunset.
trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor
    platform: state
    from: "off"
    to: "on"
condition:
  - condition: numeric_state
    below: "5"
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
action:
  - data:
      entity_id: light.kitchen_lights
      # brightness: 115
    service: light.turn_on
