alias: Kitchen lights off
description: >-
  Turn lights off when 17 minutes no motion
trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    platform: state
    to: "off"
    for:
      minutes: 17
condition: []
action:
  - data:
      entity_id: light.kitchen_lights
    action: light.turn_off
