alias: Kitchen lights on press toggle
description: >-
  Turn lights on when single-press the toggle button.
triggers:
  - entity_id: sensor.kitchen_switch_action
    trigger: state
    to: "on"
conditions: []
actions:
  - data:
      entity_id: light.kitchen_lights
      brightness_pct: 45
    action: light.turn_on
