# 1001 = button UP is held
# 1003 = button UP release
# 2001 = button DOWN is held
# 2003 = button DOWN released

alias: Kitchen lights dimming stop
description: >-
  Stop the dimming function for the kitchen lights when releasing the button down.
initial_state: "on"
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "kitchen_on_off_switch"
    event: 2003
condition: []
action:
  - data:
      entity_id: script.kitchen_lights_dimmer
    service: script.turn_off
