alias: Lights on when motion kitchen
trigger:
- entity_id: binary_sensor.presence_9
  platform: state
  from: 'off'
  to: 'on'
condition:
- condition: numeric_state
  below: '5'
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
action:
- data:
    entity_id: group.kitchen_spots
    brightness_pct: 48
  service: light.turn_on