alias: Kitchen lights brighter on hold up
description: >-
  Turn the lights brigther when hold-press the switch up.
triggers:
  - entity_id: sensor.kitchen_switch_action
    trigger: state
    to: "brightness_move_up"
conditions: []
actions:
  - data:
      entity_id: light.kitchen_lights
      brightness_step_pct: 10
    action: light.turn_on
