alias: Kitchen lights on
description: >-
  Turn lights on when there is motion after sunset.
trigger:
  - entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    platform: state
    to: "on"
condition:
  - condition: numeric_state
    below: 4
    entity_id: sun.sun
    attribute: elevation
action:
  - data:
      entity_id: light.kitchen_lights
      brightness: 115
      transition: 1
    action: light.turn_on
