# 1001 = button UP is held
# 1003 = button UP release
# 2001 = button DOWN is held
# 2003 = button DOWN released

alias: Switch dim lights kitchen
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "tradfri_on_off_switch_1"
    event: 2001
condition: []
action:
- data:
    variables:
      direction: down
      light: light.keuken_spots
  service: script.turn_on
  entity_id: script.kitchen_lights_dimmer