alias: Switch lights off kitchen
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "tradfri_on_off_switch_1"
    event: 2002
condition: []
action:
- data:
    entity_id: group.kitchen_spots
  service: light.turn_off