alias: Switch on lights kitchen
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: "tradfri_on_off_switch_1"
    event: 1002
condition: []
action:
- data:
    entity_id: light.keuken_spots
    brightness_pct: 45
  service: light.turn_on