alias: Backyard camera nightmode on
description: >-
  Turn the backyard camera nightmode on on sunset.
triggers:
  - trigger: sun
    event: sunset
    offset: "00:00:00"
conditions: []
actions:
  - data:
      entity_id: switch.backyard_camera_night_mode
    action: switch.turn_on
