alias: Backyard camera nightmode off
description: >-
  Turn the backyard camera nightmode off on sunrise.
trigger:
  - platform: sun
    event: sunrise
    offset: "00:00:00"
condition: []
action:
  - data:
      entity_id: switch.backyard_camera_night_mode
    service: switch.turn_off
