alias: Backyard camera nightmode on
description: >-
  Turn the backyard camera nightmode on on sunset.
trigger:
  - platform: sun
    event: sunset
    offset: "00:00:00"
condition: []
action:
  - data:
      entity_id: switch.backyard_camera_night_mode
    action: switch.turn_on
