alias: Backyard lights off
description: >-
  Turn lights off when there is no motion for 5 minutes.
trigger:
  - entity_id: binary_sensor.backyard_motion_sensor
    platform: state
    to: "off"
    for:
      minutes: 5
condition: []
action:
  - data:
      entity_id: light.roofspots_backyard
    service: light.turn_off
