alias: Backyard lights off
description: >-
  Turn lights off when there is no motion for 5 minutes.
triggers:
  - entity_id: binary_sensor.backyard_motion_sensor_occupancy
    trigger: state
    to: "off"
    for:
      minutes: 5
conditions: []
actions:
  - data:
      entity_id: light.backyard_spots
    action: light.turn_off
