alias: Backyard lights on
description: >-
  Turn lights on when there is motion and after sunset.
triggers:
  - entity_id: binary_sensor.backyard_motion_sensor_occupancy
    trigger: state
    to: "on"
conditions:
  - condition: numeric_state
    below: 2
    entity_id: sun.sun
    attribute: elevation
actions:
  - data:
      entity_id: light.backyard_spots
    action: light.turn_on
