alias: Lights on when motion backyard
trigger:
- entity_id: binary_sensor.presence_17
  platform: state
  from: 'off'
  to: 'on'
condition:
- condition: numeric_state
  below: '5'
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
action:
- data:
    entity_id: light.achtertuin_spots
  service: light.turn_on