alias: Alarm armed away
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'armed_away'
condition: []
action:
- data:
    entity_id: group.alarm_pending_lights
  service: light.turn_off