alias: Alarm disarmed
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'disarmed'
condition: []
action:
- data:
    entity_id: script.alarm_lights_flash_init
  service: script.turn_off
- data:
    entity_id: script.alarm_lights_flash_loop
  service: script.turn_off
- data:
    entity_id: script.alarm_pending_sound_init
  service: script.turn_off
- data:
    entity_id: script.alarm_pending_sound_loop
  service: script.turn_off
- data:
    entity_id: script.alarm_triggered_sound_init
  service: script.turn_off
- data:
    entity_id: script.alarm_triggered_sound_loop
  service: script.turn_off
- data:
    entity_id: group.alarm_lights
  service: light.turn_on