alias: Alarm triggered
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: 'triggered'
condition: []
action:
- data:
    title: '*Het alarm gaat af!*'
    message: Het alarm is afgegaan. Check direct de fotos!
  service: telegram_bot.send_message
- data:
    url: !secret still_img_frontdoor_camera
    username: !secret camera_user
    password: !secret camera_pass
    verify_ssl: false
  service: telegram_bot.send_photo
- data:
    url: !secret still_img_driveway_camera
    username: !secret camera_user
    password: !secret camera_pass
    verify_ssl: false
  service: telegram_bot.send_photo

- data:
    entity_id: script.alarm_lights_flash_init
  service: script.turn_on

- delay:
    seconds: 1
    
- data:
    entity_id: group.alarm_sound_players
    volume_level: 1
  service: media_player.volume_set
- data:
    entity_id: script.alarm_triggered_sound_init
  service: script.turn_on
